/*
 * PacketType.hpp
 *
 *  Created on: 21 avr. 2013
 *      Author: pierre
 */

#ifndef PACKETTYPE_HPP_
#define PACKETTYPE_HPP_

namespace network {

class PacketType {

public:
	enum PacketTypeFirst {
		SESSION = 0x00000000,
		GAME = 0x01000000,
		CHAT = 0x02000000
	};

	enum PacketTypeSecond {
		GAME_STAT = GAME+0x010000
	};

	enum PacketTypeFinal {
		UNDEFINED = 0x0,
		SESSION_ASKCONNECTION = SESSION+0x1,
		SESSION_ANSWERCONNECTION = SESSION+0x2,
		SESSION_ASKCHARACTER = SESSION+0x3,
		SESSION_ANSWERCHARACTER = SESSION+0x4,
		SESSION_ASKGAME = SESSION+0x5,
		SESSION_ANSWERGAME = SESSION+0x6,
		SESSION_SELECTCHARACTER = SESSION+0x7,
		SESSION_CLOSE = SESSION+0x8,
		SESSION_CREATECHARACTER = SESSION+0x9,
		SESSION_CREATEGAME = SESSION+0xA,
		SESSION_ASKJOINGAME = SESSION+0xB,
		SESSION_ANSWERJOINGAME = SESSION+0xC,
		SESSION_PLAYERJOINGAME = SESSION+0xD,
		SESSION_PLAYERQUITGAME = SESSION+0xE,
		SESSION_ASKCHANGETEAM = SESSION+0xF,
		SESSION_PLAYERCHANGETEAM = SESSION+0x10,
		SESSION_ASKQUITGAME = SESSION+0x11,
		SESSION_ASKLAUNCHGAME = SESSION+0x12,
		SESSION_ANSWERLAUNCHGAME = SESSION+0x13,
		SESSION_GAMEDELETE = SESSION+0x14,
		SESSION_NPLAYERGAME = SESSION+0x15,
		SESSION_ASKSKILL = SESSION+0x16,
		SESSION_ANSWERSKILL = SESSION+0x17,
		SESSION_ASKALLSKILL = SESSION+0x18,
		SESSION_ANSWERALLSKILL = SESSION+0x19,
		SESSION_ASKALLSTAT = SESSION+0x1A,
		SESSION_ANSWERALLSTAT = SESSION+0x1B,

		GAME_ASKREADY = GAME+0x0,
		GAME_ANSWERREADY = GAME+0x1,
		GAME_ASKMOVE = GAME+0x2,
		GAME_ANSWERMOVE = GAME+0x3,
		GAME_PLAYERMOVE = GAME+0x4,
		GAME_ASKLAUNCHSINGLETARGETSPELL = GAME+0x5,
		GAME_ANSWERLAUNCHSINGLETARGETSPELL = GAME+0x6,
		GAME_PLAYERLAUNCHSINGLETARGETSPELL = GAME+0x7,
		GAME_ASKTELEPORT = GAME+0x8,
		GAME_ANSWERTELEPORT = GAME+0x9,
		GAME_PLAYERTELEPORT = GAME+0xA,
		GAME_PLAYERDEAD = GAME+0xB,
		GAME_SETMODE = GAME+0xC,
		GAME_ASKTARGET = GAME+0xD,
		GAME_ANSWERTARGET = GAME+0xE,
		GAME_ALLSPELL = GAME+0xF,
		GAME_ADDSPELL = GAME+0x10,
		GAME_END = GAME+0x11,
		GAME_SCORE_UPGRADE = GAME+0x12,
		GAME_MODE = GAME+0x13,
		GAME_DOPHYSICALDAMAGE = GAME+0x14,
		GAME_DOMAGICALDAMAGE = GAME+0x15,
		GAME_SETMESSAGE = GAME+0x16,

		GAME_STAT_ALL = GAME_STAT+0x0,
		GAME_STAT_LIFE = GAME_STAT+0x1,
		GAME_STAT_MAXLIFE = GAME_STAT+0x2,
		GAME_STAT_MANA = GAME_STAT+0x3,
		GAME_STAT_MAXMANA = GAME_STAT+0x4,
		GAME_STAT_ATTACKSPEED = GAME_STAT+0x5,
		GAME_STAT_MOVEMENTSPEED = GAME_STAT+0x6,
		GAME_STAT_PHYSICALATTACK = GAME_STAT+0x7,
		GAME_STAT_MAGICALATTACK = GAME_STAT+0x8,
		GAME_STAT_PHYSICALARMOR = GAME_STAT+0x9,
		GAME_STAT_MAGICALARMOR = GAME_STAT+0x10,
		GAME_STAT_RANGE = GAME_STAT+0x11,

		CHAT_SENDMESSAGE = CHAT+0x0,
		CHAT_RECEIVEMESSAGE = CHAT+0x1,
		CHAT_CREATECHAT = CHAT+0x2
	};

	enum PacketContents {
		//connection
		NONEXISTENT_ACCOUNT,
		BAD_PASSWORD,
		ALREADY_LOGGED,
		LOGIN_OK,

		//direction
		DIRECTION_NONE,
		DIRECTION_NORTH,
		DIRECTION_NORTHEAST,
		DIRECTION_EAST,
		DIRECTION_SOUTHEAST,
		DIRECTION_SOUTH,
		DIRECTION_SOUTHWEST,
		DIRECTION_WEST,
		DIRECTION_NORTHWEST,

		//Faction
		FACTION_PEACEFUL,
		FACTION_AGGRESSIVE,
		FACTION_TEAM1,
		FACTION_TEAM2,

		//Chat
		CHAT_SELECTTEAM,
		CHAT_GAME,
		CHAT_ENDGAME,

		//Mode
		MODE_PVP

	};

};

}


#endif /* PACKETTYPE_HPP_ */
